//! Raw FFI bindings to the OpenZen C API.
//!
//! These types and function declarations are generated by hand from the
//! OpenZen headers (`OpenZenCAPI.h`, `ZenTypes.h`) at commit
//! `dd8d9269ccbbb5a3582ac4ecb622ae829f67aee7`.
//!
//! The companion `build.rs` clones and builds OpenZen from source so the
//! library is always available — no runtime `libloading` needed.

#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals, dead_code)]

use std::os::raw::c_char;

// ---------------------------------------------------------------------------
// Handle types (C: struct { uintptr_t handle; })
// ---------------------------------------------------------------------------

#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ZenClientHandle_t {
    pub handle: usize,
}

#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ZenSensorHandle_t {
    pub handle: usize,
}

#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ZenComponentHandle_t {
    pub handle: usize,
}

// ---------------------------------------------------------------------------
// Error / status enums
// ---------------------------------------------------------------------------

pub type ZenError = i32;
pub type ZenError_t = i32;

pub const ZenError_None: ZenError = 0;
pub const ZenError_Unknown: ZenError = 1;
pub const ZenError_IsNull: ZenError = 10;
pub const ZenError_NotNull: ZenError = 11;
pub const ZenError_WrongDataType: ZenError = 12;
pub const ZenError_BufferTooSmall: ZenError = 13;
pub const ZenError_InvalidArgument: ZenError = 14;
pub const ZenError_NotSupported: ZenError = 15;
pub const ZenError_AlreadyInitialized: ZenError = 20;
pub const ZenError_NotInitialized: ZenError = 21;
pub const ZenError_Device_ListingFailed: ZenError = 32;
pub const ZenError_Device_Listing: ZenError = 35;
pub const ZenError_InvalidClientHandle: ZenError = 2000;
pub const ZenError_InvalidSensorHandle: ZenError = 2001;
pub const ZenError_InvalidComponentHandle: ZenError = 2002;

pub const ZenError_Io_GetFailed: ZenError = 30;

pub type ZenSensorInitError = i32;

pub const ZenSensorInitError_None: ZenSensorInitError = 0;
pub const ZenSensorInitError_ConnectFailed: ZenSensorInitError = 9;
pub const ZenSensorInitError_Timeout: ZenSensorInitError = 14;

// ---------------------------------------------------------------------------
// Event types
// ---------------------------------------------------------------------------

pub type ZenEventType = i32;

pub const ZenEventType_None: ZenEventType = 0;
pub const ZenEventType_SensorFound: ZenEventType = 1;
pub const ZenEventType_SensorListingProgress: ZenEventType = 2;
pub const ZenEventType_SensorDisconnected: ZenEventType = 3;
pub const ZenEventType_ImuData: ZenEventType = 100;
pub const ZenEventType_GnssData: ZenEventType = 200;

// ---------------------------------------------------------------------------
// Property constants
// ---------------------------------------------------------------------------

pub type ZenProperty_t = i32;
pub type ZenPropertyType = i32;

// IMU properties
pub const ZenImuProperty_StreamData: ZenProperty_t = 1000;
pub const ZenImuProperty_SamplingRate: ZenProperty_t = 1001;
pub const ZenImuProperty_GyrUseAutoCalibration: ZenProperty_t = 1022;

// Log levels
pub type ZenLogLevel = i32;
pub const ZenLogLevel_Off: ZenLogLevel = 0;
pub const ZenLogLevel_Error: ZenLogLevel = 1;
pub const ZenLogLevel_Warning: ZenLogLevel = 2;
pub const ZenLogLevel_Info: ZenLogLevel = 3;
pub const ZenLogLevel_Debug: ZenLogLevel = 4;

// ---------------------------------------------------------------------------
// Data structures — must match C layout exactly (#[repr(C)])
// ---------------------------------------------------------------------------

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ZenSensorDesc {
    pub name: [c_char; 256],
    pub serialNumber: [c_char; 64],
    pub ioType: [c_char; 64],
    pub identifier: [c_char; 64],
    pub baudRate: u32,
}

impl Default for ZenSensorDesc {
    fn default() -> Self {
        // SAFETY: All-zero is valid for this POD struct.
        unsafe { std::mem::zeroed() }
    }
}

impl ZenSensorDesc {
    /// Read the `name` field as a UTF-8 string (stops at first NUL).
    pub fn name_str(&self) -> &str {
        c_char_array_to_str(&self.name)
    }

    /// Read the `serialNumber` field as a UTF-8 string (stops at first NUL).
    pub fn serial_number_str(&self) -> &str {
        c_char_array_to_str(&self.serialNumber)
    }

    /// Read the `ioType` field as a UTF-8 string.
    pub fn io_type_str(&self) -> &str {
        c_char_array_to_str(&self.ioType)
    }

    /// Read the `identifier` field as a UTF-8 string.
    pub fn identifier_str(&self) -> &str {
        c_char_array_to_str(&self.identifier)
    }
}

fn c_char_array_to_str(arr: &[c_char]) -> &str {
    let bytes: &[u8] = unsafe { std::slice::from_raw_parts(arr.as_ptr() as *const u8, arr.len()) };
    let len = bytes.iter().position(|&b| b == 0).unwrap_or(bytes.len());
    std::str::from_utf8(&bytes[..len]).unwrap_or("")
}

/// IMU data as delivered by OpenZen — field order and types match `ZenImuData` in ZenTypes.h.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct ZenImuData {
    pub frameCount: i32,
    pub timestamp: f64,
    pub a: [f32; 3],
    pub g1: [f32; 3],
    pub g2: [f32; 3],
    pub g1BiasCalib: [f32; 3],
    pub g2BiasCalib: [f32; 3],
    pub b: [f32; 3],
    pub aRaw: [f32; 3],
    pub g1Raw: [f32; 3],
    pub g2Raw: [f32; 3],
    pub bRaw: [f32; 3],
    pub w: [f32; 3],
    pub r: [f32; 3],
    pub q: [f32; 4],
    pub rotationM: [f32; 9],
    pub rotOffsetM: [f32; 9],
    pub pressure: f32,
    pub linAcc: [f32; 3],
    pub gTemp: f32,
    pub altitude: f32,
    pub temperature: f32,
    pub heaveMotion: f32,
}

/// GNSS fix type (for completeness — used in the event union).
#[repr(C)]
#[derive(Clone, Copy)]
pub struct ZenGnssData {
    pub frameCount: i32,
    pub timestamp: f64,
    pub latitude: f64,
    pub horizontalAccuracy: f64,
    pub longitude: f64,
    pub verticalAccuracy: f64,
    pub height: f64,
    pub headingOfMotion: f64,
    pub headingOfVehicle: f64,
    pub headingAccuracy: f64,
    pub velocity: f64,
    pub velocityAccuracy: f64,
    pub fixType: i32,
    pub carrierPhaseSolution: i32,
    pub numberSatellitesUsed: u8,
    pub year: u16,
    pub month: u8,
    pub day: u8,
    pub hour: u8,
    pub minute: u8,
    pub second: u8,
    pub nanoSecondCorrection: i32,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ZenEventData_SensorDisconnected {
    pub error: ZenError_t,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ZenEventData_SensorListingProgress {
    pub progress: f32,
    pub complete: c_char,
}

/// Event-data union — only one variant is valid per event (discriminated by `eventType`).
#[repr(C)]
#[derive(Clone, Copy)]
pub union ZenEventData {
    pub imuData: ZenImuData,
    pub gnssData: ZenGnssData,
    pub sensorDisconnected: ZenEventData_SensorDisconnected,
    pub sensorFound: ZenSensorDesc,
    pub sensorListingProgress: ZenEventData_SensorListingProgress,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ZenEvent {
    pub eventType: ZenEventType,
    pub sensor: ZenSensorHandle_t,
    pub component: ZenComponentHandle_t,
    pub data: ZenEventData,
}

// ---------------------------------------------------------------------------
// C API function declarations
// ---------------------------------------------------------------------------

extern "C" {
    // Initialization / shutdown
    pub fn ZenInit(outHandle: *mut ZenClientHandle_t) -> ZenError;
    pub fn ZenShutdown(handle: ZenClientHandle_t) -> ZenError;

    // Logging
    pub fn ZenSetLogLevel(logLevel: ZenLogLevel) -> ZenError;

    // Sensor discovery
    pub fn ZenListSensorsAsync(handle: ZenClientHandle_t) -> ZenError;

    // Sensor connection
    pub fn ZenObtainSensor(
        clientHandle: ZenClientHandle_t,
        desc: *const ZenSensorDesc,
        outSensorHandle: *mut ZenSensorHandle_t,
    ) -> ZenSensorInitError;

    pub fn ZenObtainSensorByName(
        clientHandle: ZenClientHandle_t,
        ioType: *const c_char,
        sensorIdentifier: *const c_char,
        baudRate: u32,
        outSensorHandle: *mut ZenSensorHandle_t,
    ) -> ZenSensorInitError;

    pub fn ZenReleaseSensor(
        clientHandle: ZenClientHandle_t,
        sensorHandle: ZenSensorHandle_t,
    ) -> ZenError;

    // Event queue
    pub fn ZenPollNextEvent(
        handle: ZenClientHandle_t,
        outEvent: *mut ZenEvent,
    ) -> bool;

    pub fn ZenWaitForNextEvent(
        handle: ZenClientHandle_t,
        outEvent: *mut ZenEvent,
    ) -> bool;

    // Components
    pub fn ZenSensorComponents(
        clientHandle: ZenClientHandle_t,
        sensorHandle: ZenSensorHandle_t,
        componentType: *const c_char,
        outComponentHandles: *mut *mut ZenComponentHandle_t,
        outLength: *mut usize,
    ) -> ZenError;

    pub fn ZenSensorComponentsByNumber(
        clientHandle: ZenClientHandle_t,
        sensorHandle: ZenSensorHandle_t,
        componentType: *const c_char,
        number: usize,
        outComponentHandle: *mut ZenComponentHandle_t,
    ) -> ZenError;

    // Component properties — set
    pub fn ZenSensorComponentSetBoolProperty(
        clientHandle: ZenClientHandle_t,
        sensorHandle: ZenSensorHandle_t,
        componentHandle: ZenComponentHandle_t,
        property: ZenProperty_t,
        value: bool,
    ) -> ZenError;

    pub fn ZenSensorComponentSetInt32Property(
        clientHandle: ZenClientHandle_t,
        sensorHandle: ZenSensorHandle_t,
        componentHandle: ZenComponentHandle_t,
        property: ZenProperty_t,
        value: i32,
    ) -> ZenError;

    pub fn ZenSensorComponentSetFloatProperty(
        clientHandle: ZenClientHandle_t,
        sensorHandle: ZenSensorHandle_t,
        componentHandle: ZenComponentHandle_t,
        property: ZenProperty_t,
        value: f32,
    ) -> ZenError;

    // Component properties — get
    pub fn ZenSensorComponentGetBoolProperty(
        clientHandle: ZenClientHandle_t,
        sensorHandle: ZenSensorHandle_t,
        componentHandle: ZenComponentHandle_t,
        property: ZenProperty_t,
        outValue: *mut bool,
    ) -> ZenError;

    pub fn ZenSensorComponentGetInt32Property(
        clientHandle: ZenClientHandle_t,
        sensorHandle: ZenSensorHandle_t,
        componentHandle: ZenComponentHandle_t,
        property: ZenProperty_t,
        outValue: *mut i32,
    ) -> ZenError;

    // Sensor info
    pub fn ZenSensorIoType(
        clientHandle: ZenClientHandle_t,
        sensorHandle: ZenSensorHandle_t,
    ) -> *const c_char;

    pub fn ZenSensorName(
        clientHandle: ZenClientHandle_t,
        sensorHandle: ZenSensorHandle_t,
    ) -> *const c_char;
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use std::mem;

    #[test]
    fn handle_sizes_match_uintptr() {
        assert_eq!(mem::size_of::<ZenClientHandle_t>(), mem::size_of::<usize>());
        assert_eq!(mem::size_of::<ZenSensorHandle_t>(), mem::size_of::<usize>());
        assert_eq!(mem::size_of::<ZenComponentHandle_t>(), mem::size_of::<usize>());
    }

    #[test]
    fn sensor_desc_name_extraction() {
        let mut desc = ZenSensorDesc::default();
        let name = b"LPMS-IG1-01234";
        for (i, &byte) in name.iter().enumerate() {
            desc.name[i] = byte as c_char;
        }
        assert_eq!(desc.name_str(), "LPMS-IG1-01234");
    }

    #[test]
    fn event_type_constants_match_header() {
        assert_eq!(ZenEventType_SensorFound, 1);
        assert_eq!(ZenEventType_SensorListingProgress, 2);
        assert_eq!(ZenEventType_ImuData, 100);
        assert_eq!(ZenEventType_GnssData, 200);
    }

    #[test]
    fn imu_property_constants() {
        assert_eq!(ZenImuProperty_StreamData, 1000);
        assert_eq!(ZenImuProperty_SamplingRate, 1001);
    }
}
